package(default_visibility = ["//visibility:public"])

filegroup(
    name = "pyzip_template",
    srcs = ["py_spark.sh.template"]
)

filegroup(
    name = "pylint_rcfile",
    srcs = ["pylint.rc"]
)

py_binary(
    name = "pyzip",
    srcs = ["pyzip.py"],
)

