package(default_visibility = ["//visibility:public"])

py_library(
    name = "python",
    srcs = glob(["*.py"]),
    imports = ["."],
    deps = [
        "//utils/python/sparkel",
        "//utils/python/sparkel/utils",
    ],
)

py_library(
    name = "utils",
    srcs = glob(["*.py"]),
    imports = ["."],
    deps = [
        "//utils/python/sparkel",
        "//utils/python/sparkel/utils",
    ],
)
